name: Node.js Tests

# Déclenchement du workflow
on:
  push:
    branches:
      - main
  pull_request:

# Définition des jobs
jobs:
  test:
    runs-on: ubuntu-22.04  # Utilise un environnement Ubuntu

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Spécifie la version de Node.js

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Lancer les tests unitaires
      - name: Run tests
        run: npm test
