name: Téléchargement d’Artéfacts

on:
  push:
    branches:
      - main

jobs:
  upload_artifact:
    runs-on: ubuntu-22.04

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      # Étape 2 : Créer un fichier texte
      - name: Générer un fichier rapport
        run: echo "Rapport d'analyse" > report.txt

      # Étape 3 : Télécharger le fichier comme artéfact
      - name: Téléchargement de l’artéfact
        uses: actions/upload-artifact@v3
        with:
          name: rapport-analyse  # Nom de l’artéfact
          path: report.txt
