name: Utilisation des Secrets

on:
  push:
    branches:
      - main

jobs:
  use_secrets:
    runs-on: ubuntu-22.04

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      # Étape 2 : Afficher le secret (masqué dans les logs)
      - name: Afficher la clé API
        env:
          MY_SECRET: ${{ secrets.MYKEY }}
        run: |
          echo "La clé API est : $MY_SECRET"
