name: Workflow avec Variable d'Environnement

on:
  push:
    branches:
      - main

jobs:
  environment_variable:
    runs-on: ubuntu-22.04
    env: # Définition des variables d'environnement
      MESSAGE: "Déploiement réussi"

    steps:
      # Étape 1 : Vérification de l'environnement
      - name: Afficher la variable MESSAGE
        run: echo "$MESSAGE"
